# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.13-slim

WORKDIR /app

# Copy local code to the container image.
COPY . .

# Install dependencies
RUN pip install --upgrade pip \
    && pip install httpx "mcp[cli]>=1.5.0"

# Run the MCP server
CMD [ "python", "main.py" ]
